name: Tagger

on:
  push:
    branches: [ "main" ]
    paths:
      - tagger/**
      - .github/workflows/tagger.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - tagger/**
      - .github/workflows/tagger.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  firmware_tests:
    name: Firmware Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tagger/firmware
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          tagger/firmware
    - name: Check
      run: cargo check
    - name: Build
      run: cargo build --verbose --release
    # TODO: re-enable once we have tests
    # - name: Run tests
    #   run: cargo test --verbose
