name: Tagger

on:
  push:
    branches: [ "main" ]
    paths:
      - tagger/**
      - .github/workflows/tagger.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - tagger/**
      - .github/workflows/tagger.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  firmware_tests:
    name: Firmware Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tagger/firmwares
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verboses
